export const MOCK_CANVAS_CONTEXT = {
    algorithm: 'HMACSHA256',
    userId: '005xx000001Svwo',
    client: {
        oauthToken: 'mock_oauth_token_00Dxx0000001gER',
        instanceId: '_:force_canvas_test:',
        targetOrigin: 'https://mock-instance.salesforce.com',
        instanceUrl: 'https://mock-instance.salesforce.com',
    },
    context: {
        user: {
            userId: '005xx000001Svwo',
            userName: 'testuser@example.com',
            firstName: 'Canvas',
            lastName: 'TestUser',
            email: 'testuser@example.com',
            fullName: 'Canvas TestUser',
            locale: 'en_US',
            language: 'en_US',
            timeZone: 'America/Los_Angeles',
            profileId: '00exx000001syKp',
            roleId: '00Exx000001oVAk',
            userType: 'STANDARD',
            currencyISOCode: 'USD',
            accessibilityModeEnabled: false,
            profilePhotoUrl: 'https://mock-instance.salesforce.com/profilephoto/005/F',
            isDefaultNetwork: true,
            networkId: null,
            siteUrl: null,
            siteUrlPrefix: null,
        },
        organization: {
            organizationId: '00Dxx0000001gER',
            name: 'Canvas Test Org',
            multicurrencyEnabled: false,
            namespacePrefix: null,
            currencyIsoCode: 'USD',
        },
        environment: {
            locationUrl:
                'https://mock-instance.salesforce.com/_ui/core/chatter/groups/GroupProfilePage',
            uiTheme: 'Theme3',
            dimensions: { width: '800px', height: '900px', maxWidth: '1000px', maxHeight: '2000px' },
            parameters: {},
            record: {},
            displayLocation: 'Chatter',
            sublocation: null,
            version: { season: 'SPRING', api: '60.0' },
        },
        links: {
            loginUrl: 'https://login.salesforce.com',
            chatterFeedsUrl: '/services/data/v60.0/chatter/feeds',
            chatterGroupsUrl: '/services/data/v60.0/chatter/groups',
            chatterUsersUrl: '/services/data/v60.0/chatter/users',
            enterpriseUrl: '/services/Soap/c/60.0/00Dxx0000001gER',
            metadataUrl: '/services/Soap/m/60.0/00Dxx0000001gER',
            partnerUrl: '/services/Soap/u/60.0/00Dxx0000001gER',
            restUrl: '/services/data/v60.0/',
            sobjectUrl: '/services/data/v60.0/sobjects/',
            searchUrl: '/services/data/v60.0/search/',
            queryUrl: '/services/data/v60.0/query/',
            userUrl: '/services/data/v60.0/sobjects/User/005xx000001Svwo',
        },
    },
};

export const MOCK_ACCOUNTS = [
    { Id: '001xx000003DGbY', Name: 'Acme Corporation', Industry: 'Technology', AnnualRevenue: 5000000, Website: 'https://acme.example.com' },
    { Id: '001xx000003DGbZ', Name: 'Global Industries', Industry: 'Manufacturing', AnnualRevenue: 12000000, Website: 'https://globalind.example.com' },
    { Id: '001xx000003DGba', Name: 'Pinnacle Solutions', Industry: 'Consulting', AnnualRevenue: 3200000, Website: 'https://pinnacle.example.com' },
    { Id: '001xx000003DGbb', Name: 'Stellar Dynamics', Industry: 'Aerospace', AnnualRevenue: 45000000, Website: 'https://stellar.example.com' },
    { Id: '001xx000003DGbc', Name: 'Nexus Financial', Industry: 'Financial Services', AnnualRevenue: 8700000, Website: 'https://nexusfin.example.com' },
];
